<?php

return [
    'lenovo' => 'Lenovo',
    'dell' => 'Dell',
    'hp' => 'HP',
    'hewlett packard' => 'HP',
    'cisco' => 'Cisco',
    'kingston' => 'Kingston',
    'ubiquiti' => 'Ubiquiti',
    'gigabyte' => 'Gigabyte',
    'balam rush' => 'Balam Rush',
    'logitech' => 'Logitech',
    'samsung' => 'Samsung',
    'asus' => 'ASUS',
    'acer' => 'Acer',
    'microsoft' => 'Microsoft',
    'belkin' => 'Belkin',
    'tp-link' => 'TP-Link',
    'tplink' => 'TP-Link',
    'fortinet' => 'Fortinet',
    'hikvision' => 'Hikvision',
    'western digital' => 'Western Digital',
    'seagate' => 'Seagate',
    'intel' => 'Intel',
    'amd' => 'AMD',
    'nvidia' => 'NVIDIA',
    'poly' => 'HP',
    'hp poly' => 'HP',
];
